
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CepSOAPService", targetNamespace = "http://service.dad.ifam.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CepSOAPService {


    /**
     * 
     * @param cep
     * @return
     *     returns soap.Cep
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarCep", targetNamespace = "http://service.dad.ifam.edu.br/", className = "soap.BuscarCep")
    @ResponseWrapper(localName = "buscarCepResponse", targetNamespace = "http://service.dad.ifam.edu.br/", className = "soap.BuscarCepResponse")
    @Action(input = "http://service.dad.ifam.edu.br/CepSOAPService/buscarCepRequest", output = "http://service.dad.ifam.edu.br/CepSOAPService/buscarCepResponse")
    public Cep buscarCep(
        @WebParam(name = "cep", targetNamespace = "")
        String cep);

}
