
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CepSOAPServiceImplService", targetNamespace = "http://service.dad.ifam.edu.br/", wsdlLocation = "http://localhost:8088/cep?wsdl")
public class CepSOAPServiceImplService
    extends Service
{

    private final static URL CEPSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CEPSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CEPSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://service.dad.ifam.edu.br/", "CepSOAPServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/cep?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CEPSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CEPSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CepSOAPServiceImplService() {
        super(__getWsdlLocation(), CEPSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public CepSOAPServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CEPSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public CepSOAPServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CEPSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public CepSOAPServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CEPSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public CepSOAPServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CepSOAPServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CepSOAPService
     */
    @WebEndpoint(name = "CepSOAPServiceImplPort")
    public CepSOAPService getCepSOAPServiceImplPort() {
        return super.getPort(new QName("http://service.dad.ifam.edu.br/", "CepSOAPServiceImplPort"), CepSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CepSOAPService
     */
    @WebEndpoint(name = "CepSOAPServiceImplPort")
    public CepSOAPService getCepSOAPServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.dad.ifam.edu.br/", "CepSOAPServiceImplPort"), CepSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CEPSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CEPSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CEPSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
